<?php

use Illuminate\Database\Seeder;

class CustomizedDataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-02-14 15:57:08',
                'updated_at' => '2019-02-14 15:57:08',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-02-14 15:57:08',
                'updated_at' => '2019-02-14 15:57:08',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-02-14 15:57:08',
                'updated_at' => '2019-02-14 15:57:08',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'categories',
                'slug' => 'categories',
                'display_name_singular' => 'Category',
                'display_name_plural' => 'Categories',
                'icon' => 'voyager-categories',
                'model_name' => 'TCG\\Voyager\\Models\\Category',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-02-14 15:57:09',
                'updated_at' => '2019-02-14 15:57:09',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'posts',
                'slug' => 'posts',
                'display_name_singular' => 'Post',
                'display_name_plural' => 'Posts',
                'icon' => 'voyager-news',
                'model_name' => 'TCG\\Voyager\\Models\\Post',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-02-14 15:57:09',
                'updated_at' => '2019-02-14 15:57:09',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'pages',
                'slug' => 'pages',
                'display_name_singular' => 'Page',
                'display_name_plural' => 'Pages',
                'icon' => 'voyager-file-text',
                'model_name' => 'TCG\\Voyager\\Models\\Page',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-02-14 15:57:09',
                'updated_at' => '2019-02-14 15:57:09',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'students',
                'slug' => 'students',
                'display_name_singular' => 'Student',
                'display_name_plural' => 'Students',
                'icon' => 'voyager-people',
                'model_name' => 'App\\Student',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => 'test desc testtttttttttttttttttttt..',
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":"student_no"}',
                'created_at' => '2019-02-14 15:57:58',
                'updated_at' => '2019-02-15 11:32:36',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'rooms',
                'slug' => 'rooms',
                'display_name_singular' => 'Room',
                'display_name_plural' => 'Rooms',
                'icon' => 'voyager-categories',
                'model_name' => 'App\\Room',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-02-15 07:03:51',
                'updated_at' => '2019-02-15 09:12:10',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'faculties',
                'slug' => 'faculties',
                'display_name_singular' => 'Faculty',
                'display_name_plural' => 'Faculties',
                'icon' => 'voyager-group',
                'model_name' => 'App\\Faculty',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-02-15 11:02:30',
                'updated_at' => '2019-02-15 11:32:18',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'subjects',
                'slug' => 'subjects',
                'display_name_singular' => 'Subject',
                'display_name_plural' => 'Subjects',
                'icon' => 'voyager-book',
                'model_name' => 'App\\Subject',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-02-15 17:10:41',
                'updated_at' => '2019-02-15 17:28:48',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'semesters',
                'slug' => 'semesters',
                'display_name_singular' => 'Semester',
                'display_name_plural' => 'Semesters',
                'icon' => 'voyager-milestone',
                'model_name' => 'App\\Semester',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"description","order_display_column":"description","order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-02-15 17:31:34',
                'updated_at' => '2019-02-15 18:04:29',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'departments',
                'slug' => 'departments',
                'display_name_singular' => 'Department',
                'display_name_plural' => 'Departments',
                'icon' => 'voyager-archive',
                'model_name' => 'App\\Department',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-02-16 07:51:10',
                'updated_at' => '2019-02-16 07:53:05',
            ),
            12 => 
            array (
                'id' => 15,
                'name' => 'courses',
                'slug' => 'courses',
                'display_name_singular' => 'Course',
                'display_name_plural' => 'Courses',
                'icon' => 'voyager-treasure',
                'model_name' => 'App\\Course',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-02-19 06:06:00',
                'updated_at' => '2019-02-19 06:08:36',
            ),
        ));
        
        
    }
}